export class User {
  constructor(
    public id?: string,
    public idkey?: string,
    public fullname?: string,
    public phone?: string,
    public birth_day?: string,
    public address?: string,
    public country?: string,
    public username?: string,
    public email?: string,
    public status?: string,
    public status_working?: string,
    public started_at?: string,
    public ended_at?: string,
    public department?: number[],
    public role?: { name: string; permissions: string[] },
    public position_id?: string,
    public position_name?: string,
    public time_off_hours?: string,
    public image?: string,
    public image_root?: string,
    public updated_at?: string,
    public leader_id?: string,
    public leader_idKey?: string,
    public password_changed?: string,
    public leader_name?: string,
    public gender?: string,
    public last_year_time_off?: string,
    public hide_notification_to?: string | null,
    public allocated_hour?: string
  ) {}
}
